### ISSUE TITLE
pickle.load(bz2.BZ2File(options.rxnorm, 'r'))   causes "IOError: invalid data stream"

### ISSUE THREAD

**Issue by scheid** [jherskovic/MedRec#4]
I am attempting to get up and running with the MedRec algorithm.  I have the UMLS installed and ran the generate_rxnorm_file.py on the installed UMLS. This all seemed to go fine; I did not get any errors.

However when I attempt to run the reconcile.py file in demo mode (e.g., with no parameters), I get an error: "IOError: invalid data stream".

This is happening on line 273 in reconcile.py, which is this command:

rx = pickle.load(bz2.BZ2File(options.rxnorm, 'r'))

When I examine the generate_rxnorm_file.py , file, it seems like the file that is being dumped to at the very end of the file is _not_ being bz2 compressed, but is just an uncompressed file.  However, when I try to load the pickle file in reconcile.py as an uncompressed file, I get a different error, that there is an incorrect field reference.

**Comment by scheid** [comment]
So, to provide a bit more detail:

If I assume that the rxnorm.pickle.bz2 file is not in fact bz2 compressed, but is just an uncompressed pickle file, I change this line:

rx = pickle.load(bz2.BZ2File(options.rxnorm, 'r'))

to this:

myRxFile = open(options.rxnorm, "r");
rx = pickle.load(myRxFile); 

Then when I run the script, I get the error below.  Here is the exact stack trace that I get:

Traceback (most recent call last):
  File "/Library/WebServer/Documents/medrec-master/reconcile.py", line 349, in <module>
    main()
  File "/Library/WebServer/Documents/medrec-master/reconcile.py", line 292, in main
    rx = pickle.load(myRxFile); 
  File "/Library/WebServer/Documents/medrec-master/rxnorm.py", line 174, in **setstate**
    self.concepts = shelve.open(self._concepts_file, flag='r')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 239, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 223, in __init__
    Shelf.**init**(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 82, in open
    mod = **import**(result)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/dbhash.py", line 7, in <module>
    import bsddb
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bsddb/**init**.py", line 67, in <module>
    import _bsddb
ImportError: No module named _bsddb
Exception AttributeError: "'RXNORM' object has no attribute 'concepts'" in <bound method RXNORM.__del__ of <rxnorm.RXNORM object at 0x10b6f8b90>> ignored

Thank you.

**Comment by jherskovic** [comment]
There are two different things going on here.

One is that the pickle file - yeah, I do compress it in between sometimes, and the code reflects it. My bad. It is inconsistent.

The other error is just plain strange. It literally means that your Python installation isn't finding the database module it used to build the shelf. At this point I can only hypothesize that your python path is different when building the RxNorm file and running the reconcile script.

How are you running reconcile? Within an OS X web server, apparently, but how is it configured?

**Comment by scheid** [comment]
Thanks for the quick reply.

I was running this using the default Python installation in Mac OS 10.7.5, and figured out that there is an issue with the bsddb module on the Mac Python install; specifically bsddb is _not_ installed by default; it is a known issue in the community.  So that explains that error. (confusing, but I originally built the pickle files inside of Ubuntu Linux just because the Mac side was giving me a paging/out of memory when generate_rxnorm_file.py was trying to shelve the files) Eventually this won't be running on Mac OS anyway, so that's not a big deal to me.

So, then I ran it on a Windows Server 2008 box (again treating the pickle file as if it is uncompressed) and still received an error, although it was a bit different (see stack trace below).  Prior to this, I recreated the pickle files on the windows box by running generate_rxnorm_file.py from within Windows, just in case the pickle files were platform dependent in any way (I don't think they would be, but wanted to remove that possibility from my test environment)

Regarding how I am invoking reconcile.py, both in the Mac and in Windows I am simply at the command line prompt and enter "python reconcile.py" with no parameters, which should force it to use the demo data?

Thanks.

Stack trace from Windows:

 Exception AttributeError: "'RXNORM' object has no attribute 'concepts'" in <bound method RXNORM.__del__ of <rxnorm.
RXNORM object at 0x00000000024C0DD8>> ignored
Traceback (most recent call last):
  File "reconcile.py", line 352, in <module>
    main()
  File "reconcile.py", line 295, in main
    rx = pickle.load(myRxFile)
EOFError

**Comment by jherskovic** [comment]
Strange. Let me build an RxNorm file out of the latest UMLS and get back to you.

**Comment by jherskovic** [comment]
Oh, and FWIW I run this both on OS X (using a Python version from python.org) and Linux, always on 64-bit systems.

**Comment by jherskovic** [comment]
I was able to build and run the demo reconciliation on the 2012AA version of the UMLS (I had it handy, the latest one is downloading) on python 2.7.5 from python.org running on OS X 10.8.5. I'll try again with the UMLS 2013AA and report back.

**Comment by jherskovic** [comment]
Quick question: When you're moving these files around, do you include all
of the *.rxnorm.pickle files, or just rxnorm.pickle?

**Comment by scheid** [comment]
I include all of the files that are created, which, for me, are these:

concepts.rxnorm.pickle.bz2
concepts.rxnorm.pickle.bz2.by_code
ingredients.rxnorm.pickle.bz2
relationships.rxnorm.pickle.bz2
rxnorm.pickle.bz2

I have wondered if the way that I installed the UMLS could be part of the problem. BTW, I'm using 2013AA, that I just downloaded the other day.  I don't really change any of the options on their java-based installer (it's a bit confusing of an installer design, so I'm hesitate to change much of anything in it :-)  ). I ensure that rxnorm is selected, and I elect to install just the actively updated vocabularies; other than that I use its defaults.

If 2012AA works but 2013AA does not, I am fine for now going with 2012AA

**Comment by jherskovic** [comment]
I'm happy to try 2013; let me look at the settings I used on my
installation before telling you to go download 2012, though :)

**Comment by jherskovic** [comment]
I just installed 2013AA with the bog-standard defaults and everything worked. Would you mind trying this on OS X with a Python from python.org? I'm also updating the code so the filename confusion doesn't happen.

**Comment by scheid** [comment]
OK, I installed the python.org build on the Mac OS side, rebuilt the rxnorm files (using generate_rxnorm_file.py), and then ran reconcile.py, which seemed to work perfectly. So that definitely solved the problem on Mac OS.

However, I did the same sequence on the Windows Server side, and it did _not_ work.  Very bewildering. I installed the python.org build on the windows machine, used generate_rxnorm_file.py in Windows to create the pickle files, and then ran reconcile.py, which threw an error. I also tried it again with the pickle files generated on the Mac, but got the same error.  Here is the exact error:

Exception AttributeError: "'RXNORM' object has no attribute 'concepts'" in <bound method RXNORM.__del__ of <rxnorm.
RXNORM object at 0x00000000025F2DD8>> ignored
Traceback (most recent call last):
  File "reconcile.py", line 352, in <module>
    main()
  File "reconcile.py", line 295, in main
    rx = pickle.load(myRxFile)
EOFError

I did notice some odd output when running generate_rxnorm_file.py on the Windows side.

The output looked like the screen shot below:
![screen shot 2013-10-03 at 9 47 37 am](https://f.cloud.github.com/assets/5588823/1261751/03bfdacc-2c34-11e3-9eea-86e757b3ba51.png)

This output, I believe was coming from the 'for' loop at around line 123, in the 'reading relations' part.  Looks like it was hitting an exception in the try/except block.

Unfortunately, I am forced to use Windows Server 2008 as the OS; that's not under my control.

**Comment by jherskovic** [comment]
So the problem is mostly that I had never tried this under Windows, and I forgot that Windows handles text and binary files differently. All you need to do is replace open(options.rxnorm, 'r') with open(options.rxnorm, 'rb')

This will tell Python-Windows to open it as a binary file, and it'll Just Work™. Since this isn't a hindrance for OS X or Linux, I'm patching the code on github to fix it right away.

Thanks for your patience!

**Comment by jherskovic** [comment]
By the way, the ! are for relationships between concepts that aren't in the internal concept dictionary. Since the internal concept dictionary only captures RxNorm and MTH concepts, but the relationship file contains relationships for ALL UMLS source vocabularies in your installation, it is perfectly normal to get a lot of those.

Perhaps I should mute them.

**Comment by scheid** [comment]
BINGO!  adding in the 'b' option to force the pickle file to be opened in binary mode did the trick. It works on Windows, and I re-ran it on the Mac side and it still works fine there too. Not sure about Linux, but I assume that would still work.

Thank you for your persistence in helping me get this fixed. Huge help.
